cutoff: 6
max_neigh: 20
seed: 666
device: 'cuda'
Data:
  type: pt    # ase for ".traj" or pt for ".pt"
  path: .
  trainBatch: 2
  testBatch: 2
  evalBatch: 1
  trainSet: ../dataset/mp_20/train/data.pt  # your_mp_train_set_path
  testSet: ../dataset/mp_20/val/data.pt   # your_mp_valid_set_path
  evalSet: ../dataset/mp_20/test/data.pt   # your_mp_test_set_path
  numWorkers: 8
  pinMemory: True
  mean_pos: 0.0
  mean_cell: 0.0
  std_pos: 1.0
  std_cell: 1.0
  nNeighbor: 20.0
  elements: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 89, 90, 91, 92, 93, 94]
Model:
  convMode: node_edge
  updateEdge: True
  mode: simple
  nLayer: 6
  activateFn: silu
  nEmbedding: 256
  nHidden: 256
  maxRWay: 2
  maxOutWay: 2
  CutoffLayer:
    type: poly
    p: 5
  RadialLayer:
    type: besselMLP
    nBasis: 8
    nHidden: [256, 256]
    activateFn: silu
  useGraph: False
  useAtomFeat: True
  useCycle: False
Train:
  warmupSteps: 500
  allowMissing: False
  targetProp: ["direct_pos", "direct_cell"] 
  weight: [1.0, 1.0]
  loss: mae
  maxEpoch: 300
  maxStep: 10000000
  logInterval: 1
  evalEpochInterval: 1
  evalStepInterval: 1.0
  gradClip: 150
  Optimizer: 
    type: AdamW
    amsGrad: True
    weightDecay: !!float 0
    learningRate: !!float 5.12e-4
  LrScheduler:
    type: reduceOnPlateau
    lrFactor: 0.8
    patience: 5
